// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-W6Vl4yTHafLZBSNVjUc2UdNV2UU9Dg4',
    appId: '1:951474672772:web:c06f1f96f6db37eb935ed1',
    messagingSenderId: '951474672772',
    projectId: 'facebook-349',
    authDomain: 'facebook-349.firebaseapp.com',
    storageBucket: 'facebook-349.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_39SVuPI3dXJTjM7HhoK5Ieb-FXMng4',
    appId: '1:951474672772:android:66620cb8e40bc3ab935ed1',
    messagingSenderId: '951474672772',
    projectId: 'facebook-349',
    storageBucket: 'facebook-349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDymtcGzZ0fRm4yZXcGv1oI88yWx_BcQLk',
    appId: '1:951474672772:ios:092a81d6e88f5944935ed1',
    messagingSenderId: '951474672772',
    projectId: 'facebook-349',
    storageBucket: 'facebook-349.firebasestorage.app',
    androidClientId: '951474672772-6sqmigbsio2ku5oagj41i36gkqfa0d4h.apps.googleusercontent.com',
    iosClientId: '951474672772-q3ldun2h5qm7sip1slfnphlfod52jlst.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDymtcGzZ0fRm4yZXcGv1oI88yWx_BcQLk',
    appId: '1:951474672772:ios:092a81d6e88f5944935ed1',
    messagingSenderId: '951474672772',
    projectId: 'facebook-349',
    storageBucket: 'facebook-349.firebasestorage.app',
    androidClientId: '951474672772-6sqmigbsio2ku5oagj41i36gkqfa0d4h.apps.googleusercontent.com',
    iosClientId: '951474672772-q3ldun2h5qm7sip1slfnphlfod52jlst.apps.googleusercontent.com',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-W6Vl4yTHafLZBSNVjUc2UdNV2UU9Dg4',
    appId: '1:951474672772:web:ab74753e8ab36405935ed1',
    messagingSenderId: '951474672772',
    projectId: 'facebook-349',
    authDomain: 'facebook-349.firebaseapp.com',
    storageBucket: 'facebook-349.firebasestorage.app',
  );

}